### GEOMETRY
/Geometry/GanESS/gas_name XENON
/Geometry/GanESS/pressure 10. bar
/Geometry/GanESS/shielding true
/Geometry/GanESS/sh_material HDPE
/Geometry/GanESS/sh_thickn 5. cm 
/Geometry/GanESS/sphere_rad 70. cm


### GENERATOR
/Generator/SingleParticle/region SPHERE
/Generator/SingleParticle/particle neutron
/Generator/SingleParticle/min_energy 10 MeV
/Generator/SingleParticle/max_energy 20 MeV
/Generator/SingleParticle/min_costheta -1
/Generator/SingleParticle/max_costheta 1
/Generator/SingleParticle/min_phi 0.
/Generator/SingleParticle/max_phi 360.


### PHYSICS
/PhysicsList/Nexus/clustering           false
/PhysicsList/Nexus/drift                false
/PhysicsList/Nexus/electroluminescence  false


### VERBOSITY
/control/verbose   0
/run/verbose       0
/event/verbose     0
/tracking/verbose  0

/process/em/verbose 0

### CONTROL
/nexus/random_seed            -1
/nexus/persistency/start_id   0
/nexus/persistency/outputFile test
