### PHYSICS
/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics G4OpticalPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics

### PERSISTENCY MANAGER
/nexus/RegisterPersistencyManager PersistencyManager

### ACTIONS
/nexus/RegisterRunAction      DefaultRunAction
/nexus/RegisterEventAction    DefaultEventAction
/nexus/RegisterTrackingAction DefaultTrackingAction

### GEOMETRY
/nexus/RegisterGeometry GanESS

### GENERATOR
/nexus/RegisterGenerator UserGenerator

### EXTRA CONFIGURATION
/nexus/RegisterMacro macros/user_test.config.mac
