### GEOMETRY
/Geometry/GanESS/gas_name ARGON
/Geometry/GanESS/pressure 50. bar
/Geometry/GanESS/shielding true
/Geometry/GanESS/sh_material HDPE
/Geometry/GanESS/sh_thickn 10. cm
/Geometry/GanESS/sphere_rad 70. cm


### GENERATOR
/Generator/UserGenerator/radius 70. cm
/Generator/UserGenerator/user_ene_dist true
/Generator/UserGenerator/ene_file uniform10.txt

### PHYSICS
/PhysicsList/Nexus/clustering           false
/PhysicsList/Nexus/drift                false
/PhysicsList/Nexus/electroluminescence  false


### VERBOSITY
/control/verbose   0
/run/verbose       0
/event/verbose     0
/tracking/verbose  0

/process/em/verbose 0


### CONTROL
/nexus/random_seed            -1
/nexus/persistency/start_id   0
/nexus/persistency/outputFile	test
