### GEOMETRY
#/Geometry/GanESS/gas_name KRIPTON
#/Geometry/GanESS/pressure 25. bar
#/Geometry/GanESS/temperature 293. kelvin

### GENERATOR

##false se generan con energías random entre 1MeV y 2MeV

/Generator/UserGenerator/user_ene_dist true

##true: 2 MeV
/Generator/UserGenerator/mono_ene false

## ahora no lee el archivo así que este comando no hace nada
/Generator/UserGenerator/ene_file histoprueba.txt


### PHYSICS
/PhysicsList/Nexus/clustering           false
/PhysicsList/Nexus/drift                false
/PhysicsList/Nexus/electroluminescence  false


### VERBOSITY
/control/verbose   0
/run/verbose       0
/event/verbose     0
/tracking/verbose  0

/process/em/verbose 0

##ACTIONS
/Actions/ValidationTrackingAction/valid_file GammasEnergy.root


### CONTROL
/nexus/random_seed            55555
#/nexus/random_seed	      -1
/nexus/persistency/start_id   0
/nexus/persistency/outputFile Test
